backend:
  name: github
  repo: heinerbehrends/portfolio-jop
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: book
    label: Book
    folder: books
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text }
